worker_processes 1;

# error_log   "/home/koriss/Рабочий стол/test-nginx-modules/nginx-workdir/logs/error.log";
# pid         "/home/koriss/Рабочий стол/test-nginx-modules/nginx-workdir/nginx.pid";

daemon off;

events {
    worker_connections 1024;
}

http {
    # client_body_temp_path   "/home/koriss/Рабочий стол/test-nginx-modules/nginx-workdir/client_body_temp";
    # proxy_temp_path         "/home/koriss/Рабочий стол/test-nginx-modules/nginx-workdir/proxy_temp";
    # fastcgi_temp_path       "/home/koriss/Рабочий стол/test-nginx-modules/nginx-workdir/fastcgi_temp";
    # uwsgi_temp_path         "/home/koriss/Рабочий стол/test-nginx-modules/nginx-workdir/uwsgi_temp";
    # scgi_temp_path          "/home/koriss/Рабочий стол/test-nginx-modules/nginx-workdir/scgi_temp";
    # access_log              "/home/koriss/Рабочий стол/test-nginx-modules/nginx-workdir/logs/access.log";
    # error_log               "/home/koriss/Рабочий стол/test-nginx-modules/nginx-workdir/logs/error.log";

    server {
        listen 8080;

        location /hello {
            hello_world;  # ваша директива из модуля
        }
    }
}
